from django.contrib.gis import admin
from .models import *

admin.site.register(AppAggregatorRoutes, admin.OSMGeoAdmin)
admin.site.register(AppAggregatorStops, admin.OSMGeoAdmin)
admin.site.register(AppAggregatorStopsBuffer300, admin.OSMGeoAdmin)
admin.site.register(AppChoaza, admin.OSMGeoAdmin)
admin.site.register(AppCity, admin.OSMGeoAdmin)
admin.site.register(AppHospital, admin.OSMGeoAdmin)
admin.site.register(AppMergedRoutes, admin.OSMGeoAdmin)
admin.site.register(AppMesh, admin.OSMGeoAdmin)
admin.site.register(AppMesh5, admin.OSMGeoAdmin)
admin.site.register(AppRailroadYusoumitsudo, admin.OSMGeoAdmin)
admin.site.register(AppRailroadsection, admin.OSMGeoAdmin)
admin.site.register(AppRoutes, admin.OSMGeoAdmin)
admin.site.register(AppSchool, admin.OSMGeoAdmin)
admin.site.register(AppStatChoazaAge5Pop, admin.OSMGeoAdmin)
admin.site.register(AppStatChoazaTransport, admin.OSMGeoAdmin)
admin.site.register(AppStatMesh5Pop, admin.OSMGeoAdmin)
admin.site.register(AppStatMeshPop, admin.OSMGeoAdmin)
admin.site.register(AppStation, admin.OSMGeoAdmin)
admin.site.register(AppStopTimes, admin.OSMGeoAdmin)
admin.site.register(AppStops, admin.OSMGeoAdmin)
admin.site.register(AppTrips, admin.OSMGeoAdmin)
admin.site.register(AppUnkouHonsuKukan2024, admin.OSMGeoAdmin)
admin.site.register(AppUnkouHonsuKukan2024R, admin.OSMGeoAdmin)
