from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.generic.base import RedirectView
from app import login_forms, views, apis

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="login.html",
            authentication_form=login_forms.BootstrapAuthenticationForm,
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("", views.index, name="index"),
    path("gtfs_list", views.gtfs_list, name="gtfs_list"),
    path("map", views.map, name="map"),
    path(
        "api/stop_times/<str:session_id>/<str:stop_id>",
        apis.stop_times,
        name="api_stop_times",
    ),
    path(
        "api/trip_detail/<str:file_name>/<str:trip_id>",
        apis.trip_detail,
        name="api_trip_detail",
    ),
    path(
        "api/get_route_ids/<str:file_name>/<str:route_name>",
        apis.get_route_ids,
        name="api_get_route_ids",
    ),
    path(
        "api/get_route_sl_name/<str:file_name>/<str:route_id>",
        apis.get_route_sl_name,
        name="api_get_route_sl_name",
    ),
    path(
        "api/get_route_to_stop_ids/<str:file_name>/<str:route_id>",
        apis.get_route_to_stop_ids,
        name="api_get_route_to_stop_ids",
    ),
    path(
        "api/stops_on_route/<str:file_name>/<str:route_id>/<str:direction_id>",
        apis.stops_on_route,
        name="api_stops_on_route",
    ),
    path("api/gtfs_download", apis.gtfs_download, name="api_gtfs_download"),
    path("api/gtfs_upload/<str:session_id>", apis.gtfs_upload, name="api_gtfs_upload"),
    path(
        "api/jisseki_csv_upload/<str:session_id>",
        apis.jisseki_csv_upload,
        name="api_jisseki_csv_upload",
    ),
    path("api/isochrone/<str:session_id>", apis.isochrone, name="api_isochrone"),
    path("uphistory", RedirectView.as_view(url="/static/uphistory.html")),
    path(
        "api/download_exportfile", apis.download_exportfile, name="download_exportfile"
    ),
    path(
        "api/get_time_table/<str:session_id>/<str:service_id>/<str:route_id>/<str:stop_id>",
        apis.get_time_table,
        name="get_time_table",
    ),
    path(
        "api/get_uniq_service_id/<str:session_id>",
        apis.get_uniq_service_id,
        name="get_uniq_service_id",
    ),
    path(
        "api/get_route_to_trip_ids/<str:file_name>/<str:route_id>/<str:direction_id>",
        apis.get_route_to_trip_ids,
        name="get_route_to_trip_ids",
    ),
    path(
        "api/get_route_to_jisseki_data/<str:file_name>/<str:trip_id>/<str:direction_id>/<str:hour>",
        apis.get_route_to_jisseki_data,
        name="api_get_route_to_jisseki_data",
    ),
    path(
        "api/get_aggr_stop_to_stop_ids/<str:file_name>/<str:stop_id>",
        apis.aggr_stop_id_to_stop_ids,
        name="api_get_aggr_stop_id_to_stop_ids",
    ),
    path(
        "api/get_aggr_stop_to_route_ids/<str:file_name>/<str:stop_id>",
        apis.aggr_stop_id_to_route_ids,
        name="api_get_aggr_stop_id_to_route_ids",
    ),
    path(
        "api/get_route_service_to_trip_ids/<str:file_name>/<str:route_id>/<str:service_id>",
        apis.get_route_service_to_trip_ids,
        name="api_get_route_service_to_trip_ids",
    ),
    path(
        "api/get_route_service_to_jisseki_data/<str:file_name>/<str:route_id>/<str:service_id>",
        apis.get_route_service_to_jisseki_data,
        name="api_get_route_service_to_jisseki_data",
    ),
    path(
        "api/get_aggregator_routes_info/<str:file_name>/<str:service_id>/<str:prev_stop_id>/<str:next_stop_id>",
        apis.get_aggregator_routes_info,
        name="api_get_aggregator_routes_info",
    ),
    path("api/generate_pdf", apis.generate_pdf, name="api_generate_pdf"),
    path(
        "api/get_jisseki_days/<str:service_id>",
        apis.get_jisseki_days,
        name="api_get_jisseki_days",
    ),
    path(
        "api/get_jisseki_routes/<str:service_id>",
        apis.get_jisseki_routes,
        name="api_get_jisseki_routes",
    ),
    path(
        "api/get_jisseki_directions/<str:service_id>",
        apis.get_jisseki_directions,
        name="api_get_jisseki_directions",
    ),
    path(
        "api/get_jisseki_graph/<str:service_id>/<str:days>/<str:time>/<str:time_range>/<str:routes>/<str:direction>",
        apis.get_jisseki_graph,
        name="api_get_jisseki_graph",
    ),
    path(
        "api/jisseki_csv_delete/<str:session_id>",
        apis.jisseki_csv_delete,
        name="api_jisseki_csv_delete",
    ),
    path(
        "api/get_datefilter_service_ids/<str:session_id>/<str:days>",
        apis.get_datefilter_service_ids,
        name="api_get_datefilter_service_ids",
    ),
    path(
        "api/get_route_id_to_name/<str:file_name>/<str:route_id>",
        apis.get_route_id_to_name,
        name="api_get_route_id_to_name",
    ),
    path(
        "api/upload_od_data/<str:session_id>",
        apis.upload_od_data,
        name="api_upload_od_data",
    ),
    path(
        "api/get_od_data_dateonly/<str:session_id>",
        apis.get_od_data_dateonly,
        name="api_get_od_data_dateonly",
    ),
    path(
        "api/get_od_data/<str:session_id>/<str:filter_date>",
        apis.get_od_data,
        name="api_get_od_data",
    ),
    path(
        "api/od_csv_delete/<str:session_id>",
        apis.od_csv_delete,
        name="api_od_csv_delete",
    ),
    path(r"celery-progress/", include("celery_progress.urls")),
    path(
        "api/od_stopid_exists/<str:session_id>/<str:filter_date>",
        apis.od_stopid_exists,
        name="od_stopid_exists",
    ),
    path(
        "api/get_jisseki_routes2/<str:service_id>/<str:filter_date>",
        apis.get_jisseki_routes2,
        name="get_jisseki_routes2",
    ),
    path(
        "api/get_aggr_stop_to_stop_ids_with_route_id/<str:open_key>/<str:stop_id>/<str:route_id>/<str:service_id>",
        apis.get_aggr_stop_to_stop_ids_with_route_id,
        name="get_aggr_stop_to_stop_ids_with_route_id",
    ),
    path(
        "api/get_stop_to_route_ids/<str:file_name>/<str:stop_id>",
        apis.stop_id_to_route_ids,
        name="stop_id_to_route_ids",
    ),
    path(
        "api/get_route_start_end/<str:file_name>/<str:service_id>/<str:route_id>",
        apis.get_route_start_end,
        name="get_route_start_end",
    ),
    path(
        "api/get_aggr_stop_to_route_ids_with_service_id/<str:file_name>/<str:stop_id>/<str:service_id>",
        apis.get_aggr_stop_to_route_ids_with_service_id,
        name="get_aggr_stop_to_route_ids_with_service_id",
    ),
    path(
        "api/get_aggr_stop_id_from_stop_id/<str:file_name>/<str:stop_id>",
        apis.get_aggr_stop_id_from_stop_id,
        name="get_aggr_stop_id_from_stop_id",
    ),
    path(
        "api/get_route_start_end_jisseki/<str:file_name>/<str:service_id>/<str:route_id>/<str:trip_id>",
        apis.get_route_start_end_jisseki,
        name="get_route_start_end_jisseki",
    ),
    path(
        "api/get_aggr_stop_id_from_stop_name/<str:file_name>/<str:stop_name>",
        apis.get_aggr_stop_id_from_stop_name,
        name="get_aggr_stop_id_from_stop_name",
    ),
]
